// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
// ```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAs6hFR_JNoejprYt2Ffeao_iFbgV9L8Q',
    appId: '1:820779280487:web:2ed400fd059452ac360cc2',
    messagingSenderId: '820779280487',
    projectId: 'matheus-gerenciadorclientes',
    authDomain: 'matheus-gerenciadorclientes.firebaseapp.com',
    storageBucket: 'matheus-gerenciadorclientes.firebasestorage.app',
    measurementId: 'G-KW2S2VLVJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOjrzqzcStgx_pV6EZT0Z0NAq4nB4JJNM',
    appId: '1:820779280487:android:e955234f66f2410c360cc2',
    messagingSenderId: '820779280487',
    projectId: 'matheus-gerenciadorclientes',
    storageBucket: 'matheus-gerenciadorclientes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0utptTmz_YjA2UlYPBPzylQxLrs05F0Q',
    appId: '1:820779280487:ios:265ba1cf0d83d135360cc2',
    messagingSenderId: '820779280487',
    projectId: 'matheus-gerenciadorclientes',
    storageBucket: 'matheus-gerenciadorclientes.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0utptTmz_YjA2UlYPBPzylQxLrs05F0Q',
    appId: '1:820779280487:ios:265ba1cf0d83d135360cc2',
    messagingSenderId: '820779280487',
    projectId: 'matheus-gerenciadorclientes',
    storageBucket: 'matheus-gerenciadorclientes.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );
}
